### ISSUE TITLE
Description seems wrong on the page

### ISSUE THREAD

**Issue by timnew** [exentriquesolutions/nip.io#18]
I saw the description below on the page, but it doesn't make any sense and seems wrong to me:
> 0a000803.nip.io maps to 116.203.255.68

As hex number, it suppose to be `10.0.8.3` , and a simple ping test confirmed it

>⋊> ping 0a000803.nip.io 
> PING 0a000803.nip.io (10.0.8.3): 56 data bytes

**Comment by rses** [comment]
Thanks for pointing that out! :D It should be fixed now.
