### ISSUE TITLE
DNS revolve failed. Record gone! The nip.io

### ISSUE THREAD

**Issue by adolli** [exentriquesolutions/nip.io#2]
![image](https://user-images.githubusercontent.com/8390109/76700677-ea77e200-66f4-11ea-9dde-ace97dc2d5d5.png)

several minutes ago all of my services failed to resolve the *.nip.io hosts, causing all of my servers down. Is there any accident report?

My DNS is 8.8.8.8 via my router

**Comment by rses** [comment]
Should be working now:

```
$ dig nip.io @8.8.8.8

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> nip.io @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32832
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;nip.io.				IN	A

;; ANSWER SECTION:
nip.io.			20702	IN	A	116.203.255.68

;; Query time: 5 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Mar 15 12:49:16 CET 2020
;; MSG SIZE  rcvd: 51

```

There was an outage that was fixed about 15 minutes ago

**Comment by adolli** [comment]
Do you serve your own name servers of this domain?  I never head about outages of global name server providers.

**Comment by rses** [comment]
Yes, we have NS records on the domain to point to ns1.nip.io and ns2.nip.io, which is self-served.
