### ISSUE TITLE
Expired domain in config file

### ISSUE THREAD

**Issue by Zoltanpetrik** [exentriquesolutions/nip.io#22]
https://github.com/exentriquesolutions/nip.io/blob/db5bde0dd95efdaef11727f80914113184f1adf5/nipio/backend.conf#L3

I don't have the time to investigate the impact of this issue, so it might be non-issue, but the domain "lcl.io" referenced in this file is for sale.

**Comment by vanillajonathan** [comment]
For the tests I propose we use `nip.test`, `nipio.test` or `nip.io.test` or such. The `.test` is a reserved top-level domain for testing.

For the configuration file, I propose we use `example.com`. There is also `.example` which is a reserved top-level domain for documentation, so we could use `nip.example` or such.

**Comment by rses** [comment]
Yup, makes sense. I'll do this over the weekend.

**Comment by rses** [comment]
This is on master now :smiley:
