### ISSUE TITLE
Add local.gd to "Related Services"

### ISSUE THREAD

**Issue by chilts** [exentriquesolutions/nip.io#29]
Firstly, many thanks for this service, especially because `xip.io` has shut down (even though I've been using yours since before that happened). It's an awesome service and one I use everyday.

I also had a similar idea and put up `https://local.gd` a few years ago. That service is (of course) more specific than yours but I find it's a bit easier to cover a few of the more simple use-cases.

If you'd like me to, I'd be happy to do a PR to add that to the end of the list of related services. No problem if not. And thanks again for your service ... as mentioned earlier, it's one I use everyday. :)

**Comment by chilts-appsattic** [comment]
Happy for me to do a PR? Thanks.

**Comment by chilts** [comment]
Oopse, wrong account, but still me. :)

**Comment by vanillajonathan** [comment]
Sure, create a PR!

**Comment by rses** [comment]
This has been done

**Comment by chilts** [comment]
Many thanks. :)
