### ISSUE TITLE
Travis CI is not running

### ISSUE THREAD

**Issue by vanillajonathan** [exentriquesolutions/nip.io#33]
Travis CI no longer runs on travis-ci.org, you need to add it for travis-ci.com now instead.

**Comment by rses** [comment]
Ah pants. Will do it soon.

**Comment by vanillajonathan** [comment]
A friendly reminder!

**Comment by vanillajonathan** [comment]
@rses Another friendly reminder...

**Comment by rses** [comment]
Apologies for the delay but there's something broken in travis-ci.com. I can't seem to migrate the repository. So, here's what I tried:

1. Apparently I need to be part of some beta to migrate from org -> com
2. I click the "Sign up for beta" button
3. I get an email with a link to migrate and it goes 404

Then I though I might need my travis-ci.com account to be attached to a plan. But that requires me to give them my CC.

I think this is all nonsense and plenty of their docs have links that just go 404.

I think  I'll migrate to GitHub Actions. Travis CI looks like a mess at the moment.

**Comment by vanillajonathan** [comment]
You might want to contact Travis CI customer support. Maybe close this issue if you intend to not use Travis CI anymore.

**Comment by rses** [comment]
Have converted to GitHub actions and included linting as well. Over time, I've changed my mind about black, so, it's back now :rofl: Have added flak8 and mypy as well.
