### ISSUE TITLE
Add nip.io to public suffixes list

### ISSUE THREAD

**Issue by MOZGIII** [exentriquesolutions/nip.io#4]
`nip.io` should be at the public suffixes list - https://publicsuffix.org/.

This is required mainly to solve issues with Let's Encrypt certificate issuance, but it'll help with Cookie Security in browsers as well.

I'd like you to be aware of this initiative and look for approval from your part.

Here's a relevant PR I created to the public suffix repo - https://github.com/publicsuffix/list/pull/1070. Your assistance is required for DNS-level verification.

**Comment by rses** [comment]
It seems we don't qualify:

From https://github.com/publicsuffix/list/wiki/Guidelines#validation

> We do not accept entries for use as DNS wildcards, such that e.g. 1-2-3-4.foo.tld resolves as IP address 1.2.3.4.

> We do not accept entries whose sole purpose is to circumvent Let's Encrypt rate limits. They have a form you can use.

We have in the past increased Let's Encrypt rate limits for our domain. If you are hitting this limit, please do raise another issue. :)
