### ISSUE TITLE
My provider has DNS rebinding protection enabled - here's how I got a local instance working

### ISSUE THREAD

**Issue by miraculixx** [exentriquesolutions/nip.io#40]
I hope this may be helpful to someone. Thanks for an excellent service!

*Why does nip.io not work in some networks?*
Some networks block DNS rebinding. https://en.wikipedia.org/wiki/DNS_rebinding

Running a local nip.io instance
--------------------------------------------

In some networks, nip.io does not work. In this case, run your own local nip.io service. 

1. clone the nip.io repo 

       $ git clone https://github.com/exentriquesolutions/nip.io 

2. set the ENV variables in Dockerfile, and run it

        # Dockerfile for nip.io
        ...
        COPY ...
        ENV NIPIO_DOMAIN=nip.io
        ENV NIPIO_NAMESERVERS=ns1.nip.io=127.0.0.52 ns2.nip.io=127.0.0.52
        ENV NIPIO_SOA_NS=ns1.nip.io
        CMD ...

        $ nohup ./build_and_run_docker.sh &

3. add the following to /etc/systemd/resolved.conf

       # Added for resolving nip.io DNS queries 
       [Resolve]
       DNS=127.0.0.52
       Domains=~nip.io

   The DNS= IP address must match the NIPIO_NAMESERVERS in the Dockerfile.
   This directs the host's DNS service to direct all queries for the nip.io 
   domain to the DNS server running at this IP address (which is our 
   nip.io instance). Reference: https://www.freedesktop.org/software/systemd/man/resolved.conf.html

4. restart systemd resolved

       $ sudo systemctl restart systemd-resolved.service

5. try dig 

       $ dig foo-192.168.0.1.nip.io

   You should now get the 192.186.0.1 A record

**Comment by rses** [comment]
Sorry for the delay. This is a useful guide. Do you mind creating a PR as a markdown file and link it from README.md ? I can do this for you if you'd like, but would prefer credit to go to you.

**Comment by miraculixx** [comment]
I'll create a PR shortly

**Comment by stefangweichinger** [comment]
@miraculixx could you have a look at #50 , maybe? tia
