### ISSUE TITLE
nip.io status

### ISSUE THREAD

**Issue by githubcdr** [exentriquesolutions/nip.io#41]
Hi,

I noticed the domain nip.io is not online for the last few days. Is this by error or has the service been stopped?

It's hard to find any information.

Thanks!

**Comment by rses** [comment]
https://nip.io/ seems to be up and running

```
$ dig +short 123.0.0.1.nip.io
123.0.0.1
```

What are the issues that you're having? You need to give more details if we're to help you out.

**Comment by githubcdr** [comment]
Ah thanks for your reply, turned out someone added *.nip.io to a DNS blacklist..

Thanks again for this great service :)
