### ISSUE TITLE
Wrong reply from service when trying to resolve a nonexistent IP

### ISSUE THREAD

**Issue by mapolone** [exentriquesolutions/nip.io#8]
Hello,
there's an error while trying to resolve a wrong IP on purpose, using your hosted service (I'm not running it on-prem).
For example:

```
$ dig api.172.19.26.310.nip.io +short
116.203.255.68
```

it apparently happens with IP of both public and private networks.

**Comment by rses** [comment]
Thanks for reporting this.

This should be fixed now.
