### ISSUE TITLE
No IP for 192.168.0.0 block?

### ISSUE THREAD

**Issue by hamptonmoore** [exentriquesolutions/nip.io#9]
dig magic.192.168.86.201.nip.io

;; QUESTION SECTION:
;magic.192.168.86.201.nip.io.	IN	A

Is there a reason this does not work in the 192.168 IP block? This is my main usage for NIP.io :( but it doesnt work

**Comment by hamptonmoore** [comment]
Sorry it was my google wifi filtering dns results

**Comment by rses** [comment]
Yeah, there are some DNS servers that have DNS rebinding protection and does not work well with private addresses :disappointed:
